### ISSUE TITLE
March 12th, 2019 meeting

### ISSUE THREAD

**Issue by Blue-speed** [HRNUG/Organization#10]
Date: March 12th, 2019 
Speaker: Chris Haddox
Sponsor:  Progress (@sfaatz)

https://www.meetup.com/Hampton-Roads-NET-Users-Group/events/254140449/

**Comment by Haddox19** [comment]
I am interested in speaking. I have been an application developer for 9 years. Maybe I could share something to do with automated builds and releases in TFS 2018?

**Comment by 1kevgriff** [comment]
@Haddox19 Sold!  Pass us an abstract/bio?

**Comment by 1kevgriff** [comment]
@Haddox19 Can you email me at kevin@kevgriffin.com?

**Comment by 1kevgriff** [comment]
@Haddox19 Need title/abstract/bio please.

**Comment by Haddox19** [comment]
Azure DevOps: Builds, Releases and Deployment Groups

A walkthrough for creating builds and releases using TFS

Hi, I am Chris Haddox. I have been working as a .NET Application Developer since 2011. My responsibilities cover full stack development including Database, Back-end, Front-end, Server/Network Configuration, Deployments and anything else that could go wrong in an application's life cycle. I enjoy technology and engineering and like the idea of getting more involved in the developer community here in Hampton Roads.

**Comment by Haddox19** [comment]
How much time do I have to present?

**Comment by 1kevgriff** [comment]
@Haddox19 About 60-75 minutes, whatever you need.

**Comment by sfaatz** [comment]
Progress would like to sponsor. Pizza and prizes? Let me know if that works.

**Comment by 1kevgriff** [comment]
@sfaatz Fantastic!  That works!
