### ISSUE TITLE
August 11th, 2020 Meeting

### ISSUE THREAD

**Issue by 1kevgriff** [HRNUG/Organization#28]
Meeting Date: August 11th, 2020 
Speaker: Sarah Dutkiewicz (@sadukie)

**Comment by sadukie** [comment]
@1kevgriff  Count me in!

=====

Title: Azure Notebook Adventures with Sarah "sadukie" Dutkiewicz

Abstract:

Is there a relation between buy and sell values on the Animal Crossing marketplace? Does ramen style - cup, bowl, can, or bar - matter when it comes to ratings? We have the data, and we can present our findings with Azure Notebooks! Come on our data adventure and learn more about this great tool! We will look at how you can use Azure Notebooks as a learning tool, a teaching tool, and a presentation tool!

Bio:

Sarah has been in the technical realm since the late 90s. She has served in many roles – including technical support, manager, desktop support, server administrator, database administrator, developer, instructor, and mentor. Throughout her career, Sarah has found her place in the technical community – as an organizer, speaker, facilitator, author, editor, reviewer, blogger, and advocate. Due to her community involvement, Microsoft has awarded her the Microsoft Most Valuable Professional (MVP) award – 2009-2020 in Visual C# / .NET / Developer Technologies.  She is currently working on data engineering curriculum for Stage 3 Talent. Sarah loves sharing her passion for tech with the community whenever she can!

=====

If you want me to retweet anything, I'm @sadukie on Twitter.  If you need me to share something on LinkedIn, I'm https://linkedin.com/in/sadukie
