### ISSUE TITLE
September 8th, 2020 Meeting

### ISSUE THREAD

**Issue by 1kevgriff** [HRNUG/Organization#29]
Meeting Date: September 8th, 2020
Speaker: [ TODO ]  
Sponsor: [ TODO ]

**Comment by lynnaloo** [comment]
I'll do an Azure Static Web Apps talk

**Comment by 1kevgriff** [comment]
SOLD

**Comment by 1kevgriff** [comment]
@lynnaloo Abstract plskthx

**Comment by lynnaloo** [comment]
**Makeover your old web sites with Azure Static Web Apps**

Do you have some older web sites just sitting in your Github account and deployed to various PaaS providers? Have you delayed modernizing these applications because it's just too much hassle? 

Well, modernization is just another work for "makeover." Let's dust off some of those older applications and give them an Azure makeover. Together we'll explore the new Azure Static Web Apps service and then I'll show how, with a little refactoring, you can deploy your static web assets, and create dynamic "serverless" API endpoints, and have a Github actions deployment pipeline. Soon, your previously forgotten web sites will be shiny and new again and you'll have a new toolkit to deploy your new applications easily (and inexpensively) to Azure.
