### ISSUE TITLE
March 9, 2021 Meeting

### ISSUE THREAD

**Issue by drewgle** [HRNUG/Organization#35]
Meeting Date: March 9, 2021  
Speaker: Sean Killeen (@SeanKilleen)

Speakers please provide a short bio, topic and description to help us announce and promote your talk.

**Comment by jguadagno** [comment]
I'm available.  Sessions can be found at https://www.josephguadagno.net/presentations.

**Comment by SeanKilleen** [comment]
I'm available if you'd like! 

List of current sessions here: https://seankilleen.com/Talks/

But I'm definitely up to create a new abstract if the listed talks don't resonate -- feel free to reach out and we can hone in on a topic that the group may benefit from.

Thanks!

**Comment by 1kevgriff** [comment]
@SeanKilleen sold!

**Comment by 1kevgriff** [comment]
@SeanKilleen We'll reach out in Feb to settle on topic.  Thanks!

**Comment by SeanKilleen** [comment]
Hey all! Spoke with @1kevgriff and worked out a topic. Wanted to reach out here so you could prepare the meetup.

* **Title:** The Joy of Functional Testing with SpecFlow
* **Abstract:** Functional testing is a great way to ensure we're not just building the thing right, but building the right thing. In this session, we'll examine the testing pyramid, the place of functional testing, and how to write Gherkin syntax with SpecFlow to move toward acceptance test driven development. We'll use a real world sample to show a few cycles of acceptance tests in the language of the business, and talk about one project's real-world functional testing journey.
* **Bio:** Originally from the Philadelphia area, Sean is a Microsoft MVP with 15+ years of experience as a technical leader across commercial, non-profit, and federal clients. He's currently a Technical Director at CapTech Consulting; they're up to cool things, and you should ask him about it. He recently served on a modernization project that industry analysts called "more complex than the moon landing". He has also been a trainer for the CSD Certification via ScrumAlliance and for the ICP-TST/ATA certifications via ICAgile. Aside from loving his work way too much, there's a good chance he's enjoying/stressing about being a new dad, sipping great beer, exploring the Arlington area, or singing somewhere. You can find him on Twitter at @sjkilleen or blogging not nearly often enough at SeanKilleen.com. He doesn't bite; say hi!
* **Photo (if needed):** https://seankilleen.com/images/bio-photo.jpg

**Comment by SeanKilleen** [comment]
So, fun story -- Meetup hit some sort of loop when I tried to post a second comment, and now it thinks I'm over a daily comment limit of 20. So I can't post this follow-up to the group until tomorrow. (A brief aside: it provides its API response error wrapped inside of a 200 OK status code. Gah!)

So, I'll post this tomorrow.

____

I wanted to answer two of the remaining questions here:

Q: Can I use SpecFlow with Rider?
A: YES! There was a plugin released in January, which I'm very happy about. https://plugins.jetbrains.com/plugin/15957-specflow-for-rider

Q: What the heck happened with the parameterized scenario outline? Why didn't it run?
A: This drove me up a wall for a little bit, until I realized the problem was something much simpler -- I hadn't added NUnit to the project! :) While basic tests would run, the ability to enable the running of scenario outlines was blocked by not having the NUnit library itself added. Once I did that, the scenario outline picked it up. I'll add this as an example in the future so we can skip over the trivial package issue. Thanks for bearing with me!
