### ISSUE TITLE
April 13, 2021 Meeting

### ISSUE THREAD

**Issue by drewgle** [HRNUG/Organization#36]
Meeting Date: April 13, 2021  
Speaker: @lprichar

Speakers please provide a short bio, topic and description to help us announce and promote your talk.

**Comment by jguadagno** [comment]
I'm available.  Sessions can be found at https://www.josephguadagno.net/presentations.

**Comment by SeanKilleen** [comment]
I'm available if you'd like! 

List of current sessions here: https://seankilleen.com/Talks/

But I'm definitely up to create a new abstract if the listed talks don't resonate -- feel free to reach out and we can hone in on a topic that the group may benefit from.

Thanks!

**Comment by lprichar** [comment]
# Lee Richardson Bio

Lee is a Microsoft MVP and a prolific writer, speaker, and youtuber on .Net and open source topics. He has published over 100 posts to his personal blog (https://www.leerichardson.com) that have received more than half a million views since 2007. His "Code Hour" YouTube channel (https://youtube.com/leerichardson200) has attracted over 1,000 subscribers who have collectively consumed over 6,000 hours of his content. StackOverflow ranks him as a top 2% contributor. He has published dozens of articles to CodeProject with an average article rating of 4.96/5. Throughout his two decades of software development consulting in the DC area he has spoken scores of times at code camps, conferences, and user groups. He created the Siren of Shame (https://sirenofshame.com), and is a Solution Samurai at InfernoRed (http://infernoredtech.com). When not coding he enjoys running, mountain biking, smoking brisket, electronics, 3D printing, and woodworking. He is active on twitter where you can reach him @lprichar (https://twitter.com/lprichar).

## Available Presentations

### Be a Superhero on Day 1 with ABP.IO
Start your next ASP.Net project with a fully functional, attractive site with scores of best practices implemented, whether you choose MVC, Angular or Blazor as your front-end. In this session you'll learn everything you get out of the box with the successor ASP.Net Boilerplate, a wildly popular free and open source web application framework. Don't miss this opportunity to be a superhero on day 1 of your next web project.

### Blazor WebAssembly vs Angular Client Side Shootout
Which of these two powerful client-side technologies should you choose for your next project? Learn the strengths and weaknesses of Blazor WebAssembly vs. Angular as Lee experienced them while building typershark.io, a multi-player game in Blazor. Lee will delve into how Blazor works, demo it, then compare and contrast it with Angular across 10 distinct categories to give you the skills to pick the right technology for your next project.

### C#ify Your DevOps with Cake
Learn to write DevOps logic in a language the whole team can understand, and maintain: C#.  Run and test locally before compiling, testing, packaging or deploying on the CI server.  Increase maintainability, avoid DevOps spaghetti with the power of dependency management.  Debug, set breakpoints, get intellisense, and leverage the vast plugin ecosystem available to this mature, powerful, and cross platform DevOps tool.

**Comment by 1kevgriff** [comment]
@lprichar Let's go with "Blazor WebAssembly vs. Angular Client Side Shootout"
