### ISSUE TITLE
November 13th, 2018 Meeting

### ISSUE THREAD

**Issue by 1kevgriff** [HRNUG/Organization#4]
Date: November 13, 2018
Speaker: [ TODO ]
Sponsor: Progress

**Comment by sfaatz** [comment]
Progress would like to sponsor the Nov meeting. Let me know what you need to make it official :-)

**Comment by Blue-speed** [comment]
@sfaatz its official

**Comment by bmsantos** [comment]
I had a great time yesterday listening to James presentation. If there’s interest I can present about Blazor and Bionic Framework

https://bionicframework.github.io/Documentation/

**Comment by Blue-speed** [comment]
@bmsantos Yes lets have you present. Just need a short bio and presentation description.

**Comment by bmsantos** [comment]
@Blue-speed, here's the presentation description and a short bio.

### Web 3.0

By 2020 there will be almost nothing that HTML5 cannot do that Flash could. It just so happens that at this time frame Adobe is also killing Flash and the Web 2.0 should be officially complete (or close to).

So what’s next?

In 2017 Google compiled and released a Google Earth PWA[1]  app demo. The interesting part of this app was not just that it was a PWA but the fact that Google Earth was compiled from its native language (C++) to Web Assembly (or WASM). This is the technology enabling the next generation of apps. WASM was originally designed allow lower level languages like C/C++/Rust apps to be executed in a browser environment at near native speeds. Higher level languages like C# are also possible given they provide their own memory management mechanism.

In this presentation we will briefly cover:

1.	WASM: Brief Intro - https://webassembly.org
2.	Microsoft Blazor Experiment: C# on the Browser - https://blazor.net
3.	Bionic Framework Experiment: Mobile and PWA deployment for Blazor Apps - https://bionicframework.github.io/Documentation

[1] https://medium.com/google-earth/earth-on-web-the-road-to-cross-browser-7338e0f46278


### BIO

Bruno
United States

Bruno started his programing career with the simple Basic instruction of Load “” in a Sinclair ZX Spectrum and never stopped since then. He is an Open Source aficionado and interested in all topics related to computing. From Operating Systems and Programing Languages to Hardware, from Networking to Distributed Computing, from Electronics to IoT and from Algorithms to Machine Learning. Because coding is not only part of his daily job but also one of his hobbies, he quite often finds himself hacking on all things software.

Among other things, Bruno holds a BEng (Hons) in Electronic and Computer Eng., Cisco Systems CCNA and CCDA as well as a Machine Learning certification. Because the modern Web is a reflection of almost all things computing, he currently works as a Full Stack Engineer. 

Bruno lives in beautiful Chesapeake, Virginia with his wonderful wife and two very creative and messy girls, Adriana and Natalia. You can find more about Bruno’s hacks at https://github.com/bmsantos

**Comment by 1kevgriff** [comment]
@bmsantos Is it ok with you if we stream the event tonight?
