### ISSUE TITLE
September 10th, 2024 Meeting

### ISSUE THREAD

**Issue by 1kevgriff** [HRNUG/Organization#71]
Meeting Date: September 10th, 2024 Meeting
Speaker: Tom Becker 

Speakers please provide a short bio, topic and description to help us announce and promote your talk.

**Comment by RVAProgrammer** [comment]
# Domain Driven Design using CQRS and Mediatr
Writing clean, understandable code is, hopefully, the goal every time you sit down to write code, not only for your future self but for any developer that may follow you. How can we use concepts from Domain Driven Design (DDD) and CQRS to make this happen using the Mediatr package? Tonight we'll figure out how to put all of these concepts together to make that happen to benefit you now and your future self 6 months from now, because honestly that person is pretty cool.


## Bio 
Tom Becker is a Microsoft Architect at CapTech Consulting and is based in Richmond, VA where he has lived for the past 17 years after graduating from Randolph-Macon college in Ashland, VA. Tom has been working with Microsoft technologies since classic ASP all the way up to .Net 8 and everything in between including some, thankfully, dead technologies. When not in front of a computer Tom can be found out on his bike or chasing his 3 small daughters.

**Comment by 1kevgriff** [comment]
Thanks @RVAProgrammer !
